tap "homebrew/bundle"
tap "mediosz/tap"
tap "nikitabobko/tap"

brew "eza"
brew "git"
brew "neofetch"
brew "neovim"
brew "node"
brew "powerlevel10k"
brew "python@3.13"
brew "stow"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "aerospace"
cask "discord"
cask "docker"
cask "font-meslo-lg-nerd-font"
cask "google-chrome"
cask "karabiner-elements"
cask "keka"
cask "ledger-live"
cask "logitune"
cask "postman"
cask "spotify"
cask "swipeaerospace"
cask "utm"
cask "visual-studio-code"
cask "whatsapp"
cask "zoom"

