tap "mediosz/tap"
tap "nikitabobko/tap"

brew "cmake"
brew "cocoapods"
brew "eza"
brew "node"
brew "gemini-cli"
brew "git"
brew "jq"
brew "lazygit"
brew "python@3.14"
brew "libfido2"
brew "libimobiledevice"
brew "mas"
brew "neovim"
brew "openssh"
brew "pipx"
brew "pnpm"
brew "powerlevel10k"
brew "pre-commit"
brew "stow"
brew "uv"
brew "wget"
brew "xcodegen"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "1password"
cask "aerospace"
cask "arc"
cask "betterdisplay"
cask "claude-code"
cask "discord"
cask "docker-desktop"
cask "font-meslo-lg-nerd-font"
cask "google-chrome"
cask "google-drive"
cask "homerow"
cask "iterm2"
cask "karabiner-elements"
cask "keka"
cask "ledger-wallet"
cask "logitune"
cask "postman"
cask "raycast"
cask "spotify"
cask "swipeaerospace"
cask "utm"
cask "whatsapp"
cask "zoom"
mas "CrystalFetch", id: 6454431289
mas "Things", id: 904280696

go "github.com/bootdotdev/bootdev"
