tap "homebrew/bundle"
tap "nikitabobko/tap"
# Modern, maintained replacement for ls
brew "eza"
# Distributed revision control system
brew "git"
# Fast, highly customisable system info script
brew "neofetch"
# Theme for zsh
brew "powerlevel10k"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# AeroSpace is an i3-like tiling window manager for macOS
cask "aerospace@0.12.0"
# GPU-accelerated terminal emulator
cask "alacritty"
cask "font-meslo-lg-nerd-font"


vscode "bierner.markdown-mermaid"
vscode "charliermarsh.ruff"
vscode "christian-kohler.npm-intellisense"
vscode "damirka.move-syntax"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "emeraldwalk.runonsave"
vscode "enkia.tokyo-night"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.code-runner"
vscode "github.copilot"
vscode "github.vscode-github-actions"
vscode "irongeek.vscode-env"
vscode "istarwyh.writinghelper"
vscode "lzwme.lzwme-eye-care"
vscode "matangover.mypy"
vscode "mechatroner.rainbow-csv"
vscode "mhutchie.git-graph"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.autopep8"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-containers"
vscode "mysten.move"
vscode "mysten.move-trace-debug"
vscode "nomicfoundation.hardhat-solidity"
vscode "pkief.material-icon-theme"
vscode "rust-lang.rust-analyzer"
vscode "shakram02.bash-beautify"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "streetsidesoftware.code-spell-checker"
vscode "tamasfe.even-better-toml"
vscode "usernamehw.errorlens"
vscode "vscodevim.vim"
vscode "wayou.vscode-todo-highlight"
vscode "yoavbls.pretty-ts-errors"
vscode "yzhang.markdown-all-in-one"
